version: '2'
services:
    myuaa-app:
        image: myuaa
        external_links:
            - myuaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/myuaa
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
    myuaa-postgresql:
        container_name: myuaa-postgresql
        image: postgres:9.5.1
        environment:
            - POSTGRES_USER=myuaa
            - POSTGRES_PASSWORD=
    
    myuaagateway-app:
        image: myuaagateway
        external_links:
            - myuaagateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/myuaagateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
        ports:
            - 8080:8080
    myuaagateway-postgresql:
        container_name: myuaagateway-postgresql
        image: postgres:9.5.1
        environment:
            - POSTGRES_USER=myuaagateway
            - POSTGRES_PASSWORD=
    
    todo-app:
        image: todo
        external_links:
            - todo-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/todo
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
    todo-postgresql:
        container_name: todo-postgresql
        image: postgres:9.5.1
        environment:
            - POSTGRES_USER=todo
            - POSTGRES_PASSWORD=
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
    elk-elasticsearch:
        extends:
            file: elk.yml
            service: elk-elasticsearch
    elk-logstash:
        extends:
          file: elk.yml
          service: elk-logstash
    jhipster-console:
        extends:
            file: elk.yml
            service: jhipster-console
