version: '2'
services:
    myuaagateway-app:
        image: myuaagateway
        external_links:
            - myuaagateway-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - myuaagateway-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/myuaagateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    myuaagateway-postgresql:
        extends:
            file: postgresql.yml
            service: myuaagateway-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: myuaagateway-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
