version: '2'
services:
    myuaagateway-postgresql:
        container_name: myuaagateway-postgresql
        image: postgres:9.5.1
        # volumes:
        #     - ~/volumes/jhipster/myuaagateway/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=myuaagateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
